-- ============================================
-- ROAMLY DATABASE
-- PostgreSQL
-- ============================================

-- Drop tables if they already exist
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS activities;
DROP TABLE IF EXISTS trips;
DROP TABLE IF EXISTS users;


-- ============================================
-- USERS
-- ============================================

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);


-- ============================================
-- TRIPS
-- ============================================

CREATE TABLE trips (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    destination VARCHAR(255),
    start_date DATE,
    end_date DATE,
    budget INTEGER,

    CONSTRAINT fk_trips_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


-- ============================================
-- ACTIVITIES
-- ============================================

CREATE TABLE activities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id INTEGER NOT NULL,
    title VARCHAR(50),
    date DATE,
    time TIME,
    location VARCHAR(255),
    cost INTEGER,

    CONSTRAINT fk_activities_trip
        FOREIGN KEY (trip_id)
        REFERENCES trips(id)
        ON DELETE CASCADE
);


-- ============================================
-- EXPENSES
-- ============================================

CREATE TABLE expenses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id INTEGER NOT NULL,
    category VARCHAR(50),
    description VARCHAR(255),
    amount INTEGER,
    date DATE,

    CONSTRAINT fk_expenses_trip
        FOREIGN KEY (trip_id)
        REFERENCES trips(id)
        ON DELETE CASCADE
);


-- ============================================
-- USERS DATA
-- ============================================

INSERT INTO users (id, email, password_hash) VALUES
(0, 'alice@gmail.com', '$2a$12$yRfTahFcJXWkSYVnLL72y.AuKvkvUrRx5MU9svCJNu1K0qW9I4dO2'), -- Alice@01 --
(1, 'bob@gmail.com', '$2a$12$AsxzCsXkCL2Q.QLGemGuouEcAw.dC0Th03AD11z/4rcwu5/yLli/O'), -- Bobby@02 --
(2, 'candice@gmail.com', '$2a$12$yRfTahFcJXWkSYVnLL72y.AuKvkvUrRx5MU9svCJNu1K0qW9I4dO2'),
(3, 'david@gmail.com', '$2a$12$AsxzCsXkCL2Q.QLGemGuouEcAw.dC0Th03AD11z/4rcwu5/yLli/O'),
(4, 'emily@gmail.com', '$2a$12$yRfTahFcJXWkSYVnLL72y.AuKvkvUrRx5MU9svCJNu1K0qW9I4dO2'),
(5, 'james@gmail.com', '$2a$12$AsxzCsXkCL2Q.QLGemGuouEcAw.dC0Th03AD11z/4rcwu5/yLli/O');


-- ============================================
-- TRIPS DATA
-- ============================================

INSERT INTO trips
(id, user_id, destination, start_date, end_date, budget)
VALUES
(1, 0, 'Tokyo, Japan', '2026-09-10', '2026-09-18', 35000),
(2, 0, 'Seoul, South Korea', '2026-11-05', '2026-11-12', 28000),
(3, 1, 'Cape Town, South Africa', '2026-09-20', '2026-09-25', 12000),
(4, 1, 'Paris, France', '2027-01-10', '2027-01-20', 45000),
(5, 2, 'Barcelona, Spain', '2026-10-03', '2026-10-10', 24000),
(6, 2, 'Amsterdam, Netherlands', '2027-03-15', '2027-03-22', 30000),
(7, 3, 'New York, USA', '2026-12-01', '2026-12-10', 40000),
(8, 3, 'Dubai, UAE', '2027-02-05', '2027-02-10', 22000),
(9, 4, 'Cape Town, South Africa', '2026-10-15', '2026-10-20', 15000),
(10, 4, 'Mauritius', '2027-01-05', '2027-01-12', 20000),
(11, 5, 'London, UK', '2026-11-20', '2026-11-28', 38000),
(12, 5, 'Rome, Italy', '2027-04-10', '2027-04-17', 26000);


-- ============================================
-- ACTIVITIES DATA
-- ============================================

INSERT INTO activities
(id, trip_id, title, date, time, location, cost)
VALUES
(1, 1, 'Visit Shibuya Crossing', '2026-09-11', '10:00', 'Shibuya, Tokyo', 0),
(2, 1, 'Tokyo Skytree', '2026-09-12', '14:00', 'Sumida, Tokyo', 3500),
(3, 1, 'Sushi Dinner', '2026-09-13', '19:00', 'Shinjuku, Tokyo', 2500),

(4, 2, 'Gyeongbokgung Palace', '2026-11-06', '10:00', 'Seoul, South Korea', 500),
(5, 2, 'N Seoul Tower', '2026-11-07', '18:00', 'Yongsan, Seoul', 1800),
(6, 2, 'Myeongdong Shopping', '2026-11-08', '14:00', 'Myeongdong, Seoul', 0),

(7, 3, 'Table Mountain', '2026-09-21', '09:00', 'Cape Town, South Africa', 900),
(8, 3, 'V&A Waterfront', '2026-09-22', '11:00', 'Cape Town, South Africa', 0),
(9, 3, 'Robben Island Tour', '2026-09-23', '09:00', 'Robben Island, Cape Town', 600),

(10, 4, 'Eiffel Tower', '2027-01-11', '10:00', 'Paris, France', 4500),
(11, 4, 'Louvre Museum', '2027-01-12', '09:30', 'Paris, France', 3000),
(12, 4, 'Seine River Cruise', '2027-01-13', '18:00', 'Seine River, Paris', 1800),

(13, 5, 'Sagrada Familia', '2026-10-04', '10:00', 'Barcelona, Spain', 900),
(14, 5, 'Park Güell', '2026-10-05', '11:00', 'Barcelona, Spain', 500),
(15, 5, 'La Rambla', '2026-10-06', '15:00', 'La Rambla, Barcelona', 0),

(16, 6, 'Anne Frank House', '2027-03-16', '10:00', 'Amsterdam, Netherlands', 500),
(17, 6, 'Van Gogh Museum', '2027-03-17', '11:00', 'Museumplein, Amsterdam', 700),
(18, 6, 'Canal Cruise', '2027-03-18', '15:00', 'Amsterdam Canals', 600),

(19, 7, 'Statue of Liberty', '2026-12-02', '09:00', 'Liberty Island, New York', 1800),
(20, 7, 'Central Park', '2026-12-03', '10:00', 'Central Park, New York', 0),
(21, 7, 'Times Square', '2026-12-04', '19:00', 'Manhattan, New York', 0),

(22, 8, 'Burj Khalifa', '2027-02-06', '15:00', 'Downtown Dubai, UAE', 1800),
(23, 8, 'Dubai Mall', '2027-02-07', '12:00', 'Downtown Dubai, UAE', 0),
(24, 8, 'Desert Safari', '2027-02-08', '16:00', 'Dubai Desert', 2500),

(25, 9, 'Table Mountain', '2026-10-16', '09:00', 'Cape Town, South Africa', 900),
(26, 9, 'Kirstenbosch Gardens', '2026-10-17', '10:00', 'Cape Town, South Africa', 250),
(27, 9, 'Clifton Beach', '2026-10-18', '14:00', 'Clifton, Cape Town', 0),

(28, 10, 'Grand Baie Beach', '2027-01-06', '10:00', 'Grand Baie, Mauritius', 0),
(29, 10, 'Catamaran Cruise', '2027-01-07', '09:00', 'Grand Baie, Mauritius', 1800),
(30, 10, 'Chamarel Seven Coloured Earth', '2027-01-08', '11:00', 'Chamarel, Mauritius', 600),

(31, 11, 'Tower of London', '2026-11-21', '10:00', 'London, UK', 800),
(32, 11, 'British Museum', '2026-11-22', '11:00', 'London, UK', 0),
(33, 11, 'London Eye', '2026-11-23', '15:00', 'South Bank, London', 1000),

(34, 12, 'Colosseum', '2027-04-11', '09:00', 'Rome, Italy', 900),
(35, 12, 'Vatican Museums', '2027-04-12', '10:00', 'Vatican City', 1100),
(36, 12, 'Trevi Fountain', '2027-04-13', '18:00', 'Rome, Italy', 0);


-- ============================================
-- EXPENSES DATA
-- ============================================

INSERT INTO expenses
(id, trip_id, category, description, amount, date)
VALUES
(1, 1, 'Accommodation', 'Tokyo hotel - 8 nights', 12000, '2026-09-10'),
(2, 1, 'Flights', 'Return flight to Tokyo', 14000, '2026-09-10'),
(3, 1, 'Transport', 'Suica / local transport', 2000, '2026-09-11'),
(4, 1, 'Food', 'Restaurants and meals', 3500, '2026-09-13'),

(5, 2, 'Accommodation', 'Seoul hotel - 7 nights', 9000, '2026-11-05'),
(6, 2, 'Flights', 'Return flight to Seoul', 11000, '2026-11-05'),
(7, 2, 'Transport', 'Subway and buses', 1500, '2026-11-06'),
(8, 2, 'Food', 'Restaurants and street food', 2500, '2026-11-08'),

(9, 3, 'Accommodation', 'Cape Town hotel - 5 nights', 5000, '2026-09-20'),
(10, 3, 'Transport', 'Car rental', 2500, '2026-09-20'),
(11, 3, 'Food', 'Restaurants and meals', 1800, '2026-09-21'),
(12, 3, 'Activities', 'Robben Island and Table Mountain', 1500, '2026-09-23'),

(13, 4, 'Accommodation', 'Paris hotel - 10 nights', 16000, '2027-01-10'),
(14, 4, 'Flights', 'Return flight to Paris', 18000, '2027-01-10'),
(15, 4, 'Transport', 'Metro and local transport', 2500, '2027-01-11'),
(16, 4, 'Food', 'Restaurants and meals', 4500, '2027-01-13'),

(17, 5, 'Accommodation', 'Barcelona hotel - 7 nights', 8500, '2026-10-03'),
(18, 5, 'Flights', 'Return flight to Barcelona', 10000, '2026-10-03'),
(19, 5, 'Transport', 'Metro and buses', 1500, '2026-10-04'),
(20, 5, 'Food', 'Restaurants and tapas', 2500, '2026-10-06'),

(21, 6, 'Accommodation', 'Amsterdam hotel - 7 nights', 11000, '2027-03-15'),
(22, 6, 'Flights', 'Return flight to Amsterdam', 12000, '2027-03-15'),
(23, 6, 'Transport', 'Train and tram passes', 1800, '2027-03-16'),
(24, 6, 'Food', 'Restaurants and meals', 3000, '2027-03-18'),

(25, 7, 'Accommodation', 'New York hotel - 9 nights', 18000, '2026-12-01'),
(26, 7, 'Flights', 'Return flight to New York', 16000, '2026-12-01'),
(27, 7, 'Transport', 'Subway and taxis', 2500, '2026-12-02'),
(28, 7, 'Food', 'Restaurants and meals', 4000, '2026-12-04'),

(29, 8, 'Accommodation', 'Dubai hotel - 5 nights', 8500, '2027-02-05'),
(30, 8, 'Flights', 'Return flight to Dubai', 9000, '2027-02-05'),
(31, 8, 'Transport', 'Metro and taxis', 1200, '2027-02-06'),
(32, 8, 'Food', 'Restaurants and meals', 2500, '2027-02-08'),

(33, 9, 'Accommodation', 'Cape Town hotel - 5 nights', 6500, '2026-10-15'),
(34, 9, 'Transport', 'Rental car', 2500, '2026-10-15'),
(35, 9, 'Food', 'Restaurants and meals', 2200, '2026-10-18'),
(36, 9, 'Activities', 'Tours and attractions', 1500, '2026-10-17'),

(37, 10, 'Accommodation', 'Mauritius hotel - 7 nights', 9000, '2027-01-05'),
(38, 10, 'Flights', 'Return flight to Mauritius', 7500, '2027-01-05'),
(39, 10, 'Transport', 'Taxi and transfers', 1500, '2027-01-06'),
(40, 10, 'Activities', 'Catamaran cruise and tours', 2500, '2027-01-07'),

(41, 11, 'Accommodation', 'London hotel - 8 nights', 14000, '2026-11-20'),
(42, 11, 'Flights', 'Return flight to London', 15000, '2026-11-20'),
(43, 11, 'Transport', 'London Underground and buses', 2200, '2026-11-21'),
(44, 11, 'Food', 'Restaurants and meals', 3500, '2026-11-23'),

(45, 12, 'Accommodation', 'Rome hotel - 7 nights', 9000, '2027-04-10'),
(46, 12, 'Flights', 'Return flight to Rome', 13000, '2027-04-10'),
(47, 12, 'Transport', 'Metro and buses', 1500, '2027-04-11'),
(48, 12, 'Food', 'Restaurants and meals', 3000, '2027-04-13');


-- ============================================
-- RESET IDENTITY SEQUENCES
-- ============================================

SELECT setval(
    pg_get_serial_sequence('users', 'id'),
    (SELECT MAX(id) FROM users)
);

SELECT setval(
    pg_get_serial_sequence('trips', 'id'),
    (SELECT MAX(id) FROM trips)
);

SELECT setval(
    pg_get_serial_sequence('activities', 'id'),
    (SELECT MAX(id) FROM activities)
);

SELECT setval(
    pg_get_serial_sequence('expenses', 'id'),
    (SELECT MAX(id) FROM expenses)
);